Google Analytics Added
Zelig880/BooksBank pull request #73
Opened 2021-05-26 07:27 UTC by abhishek-bodapati

Resolved issue #47 

- Google Measurement ID be kept in ```GA_MEASUREMENT_ID``` in ```.env```
- Used vue-gtag package
- Added the script in ```resources/views/spa.blade.php```
- The script runs only if the MEASUREMENT_ID is available. Hopefully, this won't disturb the working of the project.
- Tested in my local website using ngrok (to tunnel local host to public URL)

2021-05-26 20:59 UTC, Zelig880 requested changes
The PR was very good.. I have just provided some comment to make sure the code is consistent with the rest..

1) Remove the extra file pushed
2) Remove the changes to package.json and Package-lock.json
3) Improve the way you call PHP method and file on the blade (worth reading about laravel blade, as you can do so much more and cleaner (you can use {{ }}, or @ for variables, withouth the need to open php block like you were doing with <?php ?>

2021-05-26 20:59 UTC, Zelig880 commented on package.json
>      "axios": "^0.21.1",
Please revert the changes to this file, i do not think you need to change the package.json and also the package-lock.json with your changes :)

2021-05-26 20:59 UTC, Zelig880 commented on resources/views/spa.blade.php
> +	if($measurement_id != 'None') {
it is always suggested to use `!==` than `!=` as php like javascript does not check its type if you just use 1 equal

2021-05-26 20:59 UTC, Zelig880 commented on resources/views/spa.blade.php
> +	?>
just to let you know, instead than declare the PHP block like you did and "echo" html, in the PHP blade you can use a much cleaner syntax like explained in this link: https://stackoverflow.com/questions/40122633/if-else-condition-in-blade-file-laravel-5-3

@if($measurement_id !== 'None')         
      <script> your script tag</script>    
@endif

2021-05-27 00:08 UTC, abhishek-bodapati commented
Sure !! I'll do the necessary changes.

2021-05-27 20:43 UTC, Zelig880 commented
This has already been merged in another patch

2021-05-27 20:43 UTC, closed without merging